FROM centos/php-72-centos7

USER root

RUN yum install -y epel-release
RUN yum install -y openvpn sed git openssl mysql
RUN ln -s /opt/rh/rh-php72/root/usr/bin/php /usr/bin/

WORKDIR /root
RUN git clone https://github.com/yevgavrikov/OpenVPN-Admin.git
WORKDIR /root/OpenVPN-Admin
RUN cp -r "./installation/scripts" "/etc/openvpn/" && chmod +x "/etc/openvpn/scripts/"* && \
    cp "./installation/server.conf" "/etc/openvpn/" && mkdir "/etc/openvpn/ccd"

# change group nogroup to group nobody ad disable client notification server restart
RUN sed -i "s/group nogroup/group nobody/" "/etc/openvpn/server.conf" && \
    sed -i "s/explicit-exit-notify 1/explicit-exit-notify 0/" "/etc/openvpn/server.conf"

# Add client to client connection if needed and presist client IP
RUN sed -i "$ a client-to-client" "/etc/openvpn/server.conf" && \
    sed -i "$ a ifconfig-pool-persist ipp.txt" "/etc/openvpn/server.conf"

# Get the rsa keys
WORKDIR /root/
RUN curl -L "https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.8/EasyRSA-3.0.8.tgz" -O && \
    tar -xaf "EasyRSA-3.0.8.tgz" && mv "EasyRSA-3.0.8" /etc/openvpn/easy-rsa && rm "EasyRSA-3.0.8.tgz"

COPY ./openvpn/docker-entrypoint.sh /usr/local/bin

# Make ip forwading and make it persistent
RUN echo "net.ipv4.ip_forward = 1" >> "/etc/sysctl.conf"
ENTRYPOINT ["docker-entrypoint.sh"]

